const els={
  input:document.getElementById("dataInput"),
  analyzeBtn:document.getElementById("analyzeBtn"),
  exampleStudyBtn:document.getElementById("exampleStudyBtn"),
  exampleIncomeBtn:document.getElementById("exampleIncomeBtn"),
  clearBtn:document.getElementById("clearBtn"),
  showPopulation:document.getElementById("showPopulation"),
  showSample:document.getElementById("showSample"),
  errorBox:document.getElementById("errorBox"),
  summaryGrid:document.getElementById("summaryGrid"),
  interpretationGrid:document.getElementById("interpretationGrid"),
  casioTableWrap:document.getElementById("casioTableWrap"),
  casioInterpretationCard:document.getElementById("casioInterpretationCard"),
  tableWrap:document.getElementById("dataTableWrap"),
  statusBadge:document.getElementById("statusBadge"),
  histogramCanvas:document.getElementById("histogramCanvas"),
  boxplotCanvas:document.getElementById("boxplotCanvas"),
  dotplotCanvas:document.getElementById("dotplotCanvas"),
  frequencyCanvas:document.getElementById("frequencyCanvas"),
  orderedLineCanvas:document.getElementById("orderedLineCanvas"),
  histogramNote:document.getElementById("histogramNote"),
  boxplotNote:document.getElementById("boxplotNote"),
  dotplotNote:document.getElementById("dotplotNote"),
  frequencyNote:document.getElementById("frequencyNote"),
  orderedLineNote:document.getElementById("orderedLineNote")
};

const colors={media:"#c92a2a",mediana:"#168a4a",q1:"#0ea5e9",q3:"#b7791f",outlier:"#991b1b",central:"#73c6b6",freq:"#0d6efd",ink:"#102033",muted:"#5f7085",line:"#9ebbd6"};
function formatNumber(v,d=9){if(v==null||Number.isNaN(v)||!Number.isFinite(v))return"—";if(Math.abs(v)<1e-12)v=0;if(Number.isInteger(v))return String(v);return Number(v.toFixed(d)).toString()}
const fmt=formatNumber;

function parsePythonList(text){const cleaned=text.replace(/[\[\]\(\)]/g," ").replace(/;/g,",").replace(/\n/g,",").trim();if(!cleaned)throw new Error("Pegá una lista con al menos dos números.");const nums=cleaned.split(",").map(x=>x.trim()).filter(Boolean).map(part=>{const v=Number(part.replace(",","."));if(!Number.isFinite(v))throw new Error(`No pude interpretar este valor como número: "${part}"`);return v});if(nums.length<2)throw new Error("Se necesitan al menos dos datos numéricos.");return nums}
function medianSorted(a){const n=a.length;if(n===0)return null;const m=Math.floor(n/2);return n%2===0?(a[m-1]+a[m])/2:a[m]}
function quartilesByHalves(sorted){const n=sorted.length,m=Math.floor(n/2),lower=sorted.slice(0,m),upper=n%2===0?sorted.slice(m):sorted.slice(m+1);return{q1:medianSorted(lower),q2:medianSorted(sorted),q3:medianSorted(upper),lowerHalf:lower,upperHalf:upper}}
function modeInfo(data){const c=new Map();for(const v of data)c.set(v,(c.get(v)||0)+1);let max=0;for(const x of c.values())max=Math.max(max,x);if(max<=1)return{modes:[],maxCount:max,text:"Sin moda"};const modes=[...c.entries()].filter(([,n])=>n===max).map(([v])=>v).sort((a,b)=>a-b);return{modes,maxCount:max,text:modes.map(v=>fmt(v)).join(", ")}}
function frequencyInfo(sorted){const map=new Map();for(const v of sorted)map.set(v,(map.get(v)||0)+1);return[...map.entries()].map(([value,count])=>({value,count}))}
function stats(raw){const sorted=[...raw].sort((a,b)=>a-b),n=sorted.length,sum=sorted.reduce((a,b)=>a+b,0),sumSquaresRaw=sorted.reduce((a,b)=>a+b**2,0),mean=sum/n,min=sorted[0],max=sorted[n-1],range=max-min,quartiles=quartilesByHalves(sorted),{q1,q2,q3,lowerHalf,upperHalf}=quartiles,iqr=q3-q1,lowerFence=q1-1.5*iqr,upperFence=q3+1.5*iqr,outliers=sorted.filter(x=>x<lowerFence||x>upperFence),nonOutliers=sorted.filter(x=>x>=lowerFence&&x<=upperFence),whiskerMin=nonOutliers.length?nonOutliers[0]:min,whiskerMax=nonOutliers.length?nonOutliers[nonOutliers.length-1]:max,deviationsSquared=sorted.map(x=>(x-mean)**2),sumSq=deviationsSquared.reduce((a,b)=>a+b,0),variancePopulation=sumSq/n,stdPopulation=Math.sqrt(variancePopulation),varianceSample=n>1?sumSq/(n-1):null,stdSample=varianceSample==null?null:Math.sqrt(varianceSample),cvPopulation=mean!==0?stdPopulation/Math.abs(mean):null,modes=modeInfo(sorted),frequencies=frequencyInfo(sorted);return{raw,sorted,n,sum,sumSquaresRaw,mean,min,max,range,q1,q2,q3,lowerHalf,upperHalf,iqr,lowerFence,upperFence,outliers,nonOutliers,whiskerMin,whiskerMax,deviationsSquared,variancePopulation,stdPopulation,varianceSample,stdSample,cvPopulation,modes,frequencies,sumSq}}
function setStatus(t){els.statusBadge.textContent=t}
function showError(m){els.errorBox.textContent=m;els.errorBox.classList.remove("hidden");setStatus("Error")}
function clearError(){els.errorBox.textContent="";els.errorBox.classList.add("hidden")}

function card(label,value,why){return`<article class="stat-card"><span class="label-mini">${label}</span><span class="value">${value}</span><p class="why">${why}</p></article>`}
function renderSummary(s){const cards=[card("n",fmt(s.n),"Cantidad total de datos cargados."),card("Suma",fmt(s.sum),"Total acumulado de todos los valores."),card("Media",fmt(s.mean),"Promedio: suma dividida por n."),card("Mediana / Q2",fmt(s.q2),"Valor central de los datos ordenados."),card("Mínimo",fmt(s.min),"Menor valor observado."),card("Máximo",fmt(s.max),"Mayor valor observado."),card("Rango",fmt(s.range),"Máximo menos mínimo."),card("Q1",fmt(s.q1),"Mediana de la mitad inferior."),card("Q3",fmt(s.q3),"Mediana de la mitad superior."),card("IQR",fmt(s.iqr),"Q3 - Q1: dispersión del 50% central."),card("Límite inferior",fmt(s.lowerFence),"Q1 - 1.5·IQR."),card("Límite superior",fmt(s.upperFence),"Q3 + 1.5·IQR."),card("Moda",s.modes.text,"Valor o valores que más se repiten."),card("Outliers",s.outliers.length?s.outliers.map(fmt).join(", "):"No hay","Valores fuera de los límites por IQR.")];if(els.showPopulation.checked){cards.push(card("Varianza poblacional",fmt(s.variancePopulation),"Promedio de distancias cuadradas usando n."));cards.push(card("Desvío poblacional",fmt(s.stdPopulation),"Raíz de la varianza poblacional."))}if(els.showSample.checked){cards.push(card("Varianza muestral",fmt(s.varianceSample),"Usa n - 1 cuando los datos son muestra."));cards.push(card("Desvío muestral",fmt(s.stdSample),"Raíz de la varianza muestral."))}cards.push(card("Coef. variación",s.cvPopulation==null?"—":`${fmt(s.cvPopulation*100)}%`,"Desvío relativo respecto de la media."));els.summaryGrid.innerHTML=cards.join("")}

function shortSum(values,mapper=x=>fmt(x)){if(values.length<=6)return values.map(mapper).join(" + ");return `${values.slice(0,4).map(mapper).join(" + ")} + ... + ${mapper(values[values.length-1])}`}
function listText(values){return `[${values.map(fmt).join(", ")}]`}
function renderCasioSection(s){const rows=[["x̄","Media o promedio","x̄ = Σx / n",`${fmt(s.sum)} / ${fmt(s.n)} = ${fmt(s.mean)}`,s.mean],["Σx","Suma total de los datos","Σx = x1 + x2 + ... + xn",`${shortSum(s.sorted)} = ${fmt(s.sum)}`,s.sum],["Σx²","Suma de cada dato elevado al cuadrado","Σx² = x1² + x2² + ... + xn²",`${shortSum(s.sorted,x=>`${fmt(x)}²`)} = ${fmt(s.sumSquaresRaw)}`,s.sumSquaresRaw],["σx²","Varianza poblacional","σx² = Σ(x - x̄)² / n",`(${shortSum(s.sorted,x=>`(${fmt(x)} - ${fmt(s.mean)})²`)}) / ${fmt(s.n)} = ${fmt(s.variancePopulation)}`,s.variancePopulation],["σx","Desviación estándar poblacional","σx = √σx²",`√${fmt(s.variancePopulation)} = ${fmt(s.stdPopulation)}`,s.stdPopulation],["sx²","Varianza muestral","sx² = Σ(x - x̄)² / (n - 1)",`(${shortSum(s.sorted,x=>`(${fmt(x)} - ${fmt(s.mean)})²`)}) / (${fmt(s.n)} - 1) = ${fmt(s.varianceSample)}`,s.varianceSample],["sx","Desviación estándar muestral","sx = √sx²",`√${fmt(s.varianceSample)} = ${fmt(s.stdSample)}`,s.stdSample],["n","Cantidad de datos","n = cantidad de valores",`La lista tiene ${fmt(s.n)} valores`,s.n],["min(x)","Valor mínimo","min(x) = primer dato ordenado",`${listText(s.sorted)} → ${fmt(s.min)}`,s.min],["Q1","Primer cuartil","Q1 = mediana de la mitad inferior",`Mitad inferior ${listText(s.lowerHalf)} → ${fmt(s.q1)}`,s.q1],["Med","Mediana o Q2","Med = mediana de toda la lista ordenada",`${listText(s.sorted)} → ${fmt(s.q2)}`,s.q2],["Q3","Tercer cuartil","Q3 = mediana de la mitad superior",`Mitad superior ${listText(s.upperHalf)} → ${fmt(s.q3)}`,s.q3],["max(x)","Valor máximo","max(x) = último dato ordenado",`${listText(s.sorted)} → ${fmt(s.max)}`,s.max]];
els.casioTableWrap.innerHTML=`<table class="casio-table"><thead><tr><th>Símbolo</th><th>Qué significa</th><th>Fórmula usada</th><th>Cálculo con los datos actuales</th><th>Resultado</th></tr></thead><tbody>${rows.map(([symbol,meaning,formula,calc,result])=>`<tr><td>${symbol}</td><td>${meaning}</td><td class="formula-cell">${formula}</td><td class="calculation-cell">${calc}</td><td class="result-cell">${fmt(result)}</td></tr>`).join("")}</tbody></table>`;
renderCasioInterpretation(s);if(window.MathJax&&typeof window.MathJax.typesetPromise==="function")window.MathJax.typesetPromise([els.casioTableWrap,els.casioInterpretationCard]).catch(()=>{})}
function renderCasioInterpretation(s){const diff=s.mean-s.q2,tolerance=Math.max(.001,Math.abs(s.q2)*.03,s.stdPopulation*.05);let center;if(Math.abs(diff)<=tolerance)center=`La media (${fmt(s.mean)}) y la mediana (${fmt(s.q2)}) son parecidas, así que el centro no parece muy desplazado.`;else if(diff>0)center=`La media (${fmt(s.mean)}) está por encima de la mediana (${fmt(s.q2)}): los valores altos empujan el promedio hacia arriba.`;else center=`La media (${fmt(s.mean)}) está por debajo de la mediana (${fmt(s.q2)}): los valores bajos empujan el promedio hacia abajo.`;const outliers=s.outliers.length?`Por regla IQR hay outlier(s): ${s.outliers.map(fmt).join(", ")}. ${s.outliers.length===1?`El valor ${fmt(s.outliers[0])} puede estar influyendo especialmente en la media.`:"Esos valores pueden estar influyendo en la media."}`:`No hay outliers por la regla IQR: límites ${fmt(s.lowerFence)} y ${fmt(s.upperFence)}.`;let spread;if(s.cvPopulation==null)spread=`Como la media es 0, conviene mirar el desvío estándar (${fmt(s.stdPopulation)}) junto con el rango (${fmt(s.range)}).`;else if(s.cvPopulation<.15)spread=`El desvío estándar poblacional (${fmt(s.stdPopulation)}) parece bajo respecto de la media: CV ${fmt(s.cvPopulation*100)}%.`;else if(s.cvPopulation<.35)spread=`El desvío estándar poblacional (${fmt(s.stdPopulation)}) es moderado respecto de la media: CV ${fmt(s.cvPopulation*100)}%.`;else spread=`El desvío estándar poblacional (${fmt(s.stdPopulation)}) parece alto respecto de la media: CV ${fmt(s.cvPopulation*100)}%.`;els.casioInterpretationCard.innerHTML=`<h3>Interpretación importante</h3><p>${center}</p><p>${outliers}</p><p>${spread}</p>`}
function renderInterpretation(s){const diff=s.mean-s.q2,left=s.q2-s.q1,right=s.q3-s.q2;let center=Math.abs(diff)<Math.max(.001,s.stdPopulation*.05)?"La media y la mediana son parecidas: el centro parece equilibrado.":s.mean>s.q2?"La media está por encima de la mediana: algunos valores altos empujan el promedio hacia arriba.":"La media está por debajo de la mediana: algunos valores bajos empujan el promedio hacia abajo.";let skew=Math.abs(right-left)<Math.max(.001,s.iqr*.10)?"Q2 está bastante centrada entre Q1 y Q3: el 50% central parece relativamente simétrico.":right>left?"El tramo Q2→Q3 es mayor que Q1→Q2: el centro se estira hacia valores altos.":"El tramo Q1→Q2 es mayor que Q2→Q3: el centro se estira hacia valores bajos.";let disp=s.iqr===0&&s.range===0?"No hay dispersión: todos los datos son iguales.":s.iqr===0?"El 50% central está concentrado, pero hay variación en los extremos.":`El 50% central está entre ${fmt(s.q1)} y ${fmt(s.q3)}, con amplitud ${fmt(s.iqr)}.`;let out=s.outliers.length?`Se detectan ${s.outliers.length} outlier(s): ${s.outliers.map(fmt).join(", ")}.`:"No se detectan outliers con la regla Q1 - 1.5·IQR / Q3 + 1.5·IQR.";els.interpretationGrid.innerHTML=`<article class="interpret-card"><strong>Centro</strong><p>${center}</p></article><article class="interpret-card"><strong>Dispersión central</strong><p>${disp}</p></article><article class="interpret-card"><strong>Asimetría</strong><p>${skew}</p></article><article class="interpret-card"><strong>Valores atípicos</strong><p>${out}</p></article>`}
function classify(v,s){if(v<s.lowerFence||v>s.upperFence)return{label:"Outlier",cls:"outlier"};if(v<s.q1)return{label:"Bajo Q1",cls:"low"};if(v>s.q3)return{label:"Sobre Q3",cls:"high"};return{label:"50% central",cls:"mid"}}
function zoneColor(v,s){const c=classify(v,s).cls;return c==="outlier"?colors.outlier:c==="low"?colors.q1:c==="high"?colors.q3:colors.mediana}
function renderTable(s){els.tableWrap.innerHTML=`<table><thead><tr><th>Índice ordenado</th><th>Valor</th><th>Valor - media</th><th>(Valor - media)²</th><th>Zona</th></tr></thead><tbody>${s.sorted.map((v,i)=>{const c=classify(v,s),d=v-s.mean;return`<tr><td>${i}</td><td>${fmt(v)}</td><td>${fmt(d)}</td><td>${fmt(d**2)}</td><td><span class="badge ${c.cls}">${c.label}</span></td></tr>`}).join("")}</tbody></table>`}

function setup(canvas,h){const dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect(),width=rect.width||canvas.clientWidth||1200;canvas.width=Math.round(width*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,width,height:h}}
function clearCanvas(ctx,w,h){ctx.clearRect(0,0,w,h)}
function domainFrom(values,pad=.08){let min=Math.min(...values),max=Math.max(...values);if(!Number.isFinite(min)||!Number.isFinite(max)){min=0;max=1}if(min===max){const spread=Math.max(1,Math.abs(min)*.2);return{min:min-spread,max:max+spread}}const span=max-min;return{min:min-span*pad,max:max+span*pad}}
function mapXFactory(domain,left,right){return v=>left+((v-domain.min)/(domain.max-domain.min))*(right-left)}
function clampValue(v,domain){return Math.max(domain.min,Math.min(domain.max,v))}
function drawXAxis(ctx,w,h,domain,mapX,bottom,left=58,right=w-24){ctx.strokeStyle=colors.line;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,bottom);ctx.lineTo(right,bottom);ctx.stroke();ctx.fillStyle=colors.muted;ctx.font="12px system-ui";ctx.textAlign="center";ctx.textBaseline="top";const ticks=6;for(let i=0;i<=ticks;i++){const val=domain.min+(domain.max-domain.min)*i/ticks,x=mapX(val);ctx.beginPath();ctx.moveTo(x,bottom);ctx.lineTo(x,bottom+6);ctx.stroke();ctx.fillText(fmt(val),x,bottom+10)}}
function drawVLine(ctx,x,y1,y2,color,label,pos="top"){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(x,y1);ctx.lineTo(x,y2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.textBaseline=pos==="bottom"?"top":"bottom";ctx.fillText(label,x,pos==="bottom"?y2+5:y1-5)}
function drawMessage(ctx,w,h,msg){clearCanvas(ctx,w,h);ctx.fillStyle="#f7fbff";ctx.fillRect(0,0,w,h);ctx.fillStyle=colors.blueDark||"#084298";ctx.font="bold 18px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(msg,w/2,h/2)}
function drawLegend(){const items={media:["Media","media"],mediana:["Mediana","mediana"],q1:["Q1","q1"],q3:["Q3","q3"],outlier:["Outlier","outlier"],central:["50% central","central"],frecuencia:["Frecuencia","frecuencia"]};const sets={histogram:["frecuencia","media","mediana","outlier"],boxplot:["central","q1","mediana","q3","outlier"],dotplot:["q1","central","q3","outlier"],frequency:["frecuencia","outlier"],ordered:["q1","mediana","q3","outlier"]};document.querySelectorAll(".chart-legend").forEach(el=>{const keys=sets[el.dataset.kind]||Object.keys(items);el.innerHTML=keys.map(k=>`<span class="legend-pill legend-${items[k][1]}"><span class="legend-swatch"></span>${items[k][0]}</span>`).join("")})}

function drawHistogram(s){const {ctx,width,height}=setup(els.histogramCanvas,500);clearCanvas(ctx,width,height);if(s.range===0){drawMessage(ctx,width,height,"Todos los datos son iguales; no hay dispersión.");els.histogramNote.innerHTML="<strong>Histograma:</strong> todos los datos caen en el mismo valor, por eso no hay intervalos distintos.";return}const top=52,bottom=height-58,left=58,right=width-26,core=s.outliers.length?s.nonOutliers:s.sorted,domain=domainFrom(core.length?core:s.sorted,.10),mapX=mapXFactory(domain,left,right);drawXAxis(ctx,width,height,domain,mapX,bottom,left,right);const binsCount=Math.min(14,Math.max(4,Math.ceil(Math.sqrt(core.length||s.n))*2)),binW=(domain.max-domain.min)/binsCount,bins=Array.from({length:binsCount},(_,i)=>({start:domain.min+i*binW,end:domain.min+(i+1)*binW,count:0}));for(const v of core){let idx=Math.floor((v-domain.min)/binW);idx=Math.max(0,Math.min(binsCount-1,idx));bins[idx].count++}const maxC=Math.max(...bins.map(b=>b.count),1),plotH=bottom-top;ctx.fillStyle="rgba(13,110,253,.18)";ctx.fillRect(left,top,right-left,plotH);for(const b of bins){const x1=mapX(b.start),x2=mapX(b.end),barW=Math.max(8,x2-x1-5),barH=b.count/maxC*(plotH-16);ctx.fillStyle="rgba(13,110,253,.72)";ctx.fillRect(x1+3,bottom-barH,barW,barH);ctx.strokeStyle="#084298";ctx.strokeRect(x1+3,bottom-barH,barW,barH);ctx.fillStyle=colors.ink;ctx.font="bold 13px system-ui";ctx.textAlign="center";ctx.textBaseline="bottom";ctx.fillText(String(b.count),x1+3+barW/2,bottom-barH-5)}drawVLine(ctx,mapX(Math.max(domain.min,Math.min(domain.max,s.mean))),top,bottom,colors.media,"Media");drawVLine(ctx,mapX(Math.max(domain.min,Math.min(domain.max,s.q2))),top,bottom,colors.mediana,"Mediana");if(s.outliers.length){ctx.fillStyle=colors.outlier;ctx.font="bold 12px system-ui";ctx.textAlign="center";s.outliers.forEach((o,i)=>{const x=o<domain.min?left+12:right-12,y=top+18+i*18;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.fillText(fmt(o),x,y-10)});els.histogramNote.innerHTML=`<strong>Histograma:</strong> las barras usan la zona sin outliers para que el gráfico no quede aplastado; los outliers aparecen en rojo al borde. Intervalos: ${binsCount}.`}else els.histogramNote.innerHTML=`<strong>Histograma:</strong> este gráfico muestra cuántos datos caen en cada intervalo. Si una barra es más alta, hay más valores concentrados ahí. Intervalos: ${binsCount}.`}
function drawBoxplot(s){const {ctx,width,height}=setup(els.boxplotCanvas,390);clearCanvas(ctx,width,height);if(s.range===0){drawMessage(ctx,width,height,"Todos los datos son iguales; no hay dispersión.");els.boxplotNote.innerHTML="<strong>Boxplot:</strong> mínimo, Q1, mediana, Q3 y máximo coinciden en el mismo valor.";return}const top=54,bottom=height-66,left=64,right=width-32,y=176,boxH=78,domainSeed=s.outliers.length?[s.whiskerMin,s.whiskerMax,s.lowerFence,s.upperFence]:[s.min,s.max,s.lowerFence,s.upperFence],domain=domainFrom(domainSeed,.08),mapX=mapXFactory(domain,left,right),plotX=v=>mapX(clampValue(v,domain));drawXAxis(ctx,width,height,domain,mapX,bottom,left,right);const lx=plotX(s.lowerFence),ux=plotX(s.upperFence),wMin=plotX(s.whiskerMin),wMax=plotX(s.whiskerMax),q1=plotX(s.q1),q2=plotX(s.q2),q3=plotX(s.q3);ctx.strokeStyle="#7aa8cf";ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(lx,top);ctx.lineTo(lx,bottom);ctx.moveTo(ux,top);ctx.lineTo(ux,bottom);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=colors.muted;ctx.font="12px system-ui";ctx.textAlign="center";ctx.fillText(`Límite inf. ${fmt(s.lowerFence)}`,lx,top-14);ctx.fillText(`Límite sup. ${fmt(s.upperFence)}`,ux,top-14);ctx.strokeStyle=colors.ink;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(wMin,y);ctx.lineTo(q1,y);ctx.moveTo(q3,y);ctx.lineTo(wMax,y);ctx.stroke();ctx.beginPath();ctx.moveTo(wMin,y-22);ctx.lineTo(wMin,y+22);ctx.moveTo(wMax,y-22);ctx.lineTo(wMax,y+22);ctx.stroke();let boxX=q1,boxW=q3-q1;if(boxW<36){boxX=q2-18;boxW=36}ctx.fillStyle="rgba(115,198,182,.32)";ctx.strokeStyle="#0f766e";ctx.lineWidth=2;ctx.fillRect(boxX,y-boxH/2,boxW,boxH);ctx.strokeRect(boxX,y-boxH/2,boxW,boxH);ctx.strokeStyle=colors.mediana;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(q2,y-boxH/2);ctx.lineTo(q2,y+boxH/2);ctx.stroke();s.outliers.forEach(o=>{const x=plotX(o);ctx.fillStyle=colors.outlier;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText(fmt(o),x,o<domain.min?y-30:y+42)});[["Min",s.whiskerMin,wMin,colors.ink],["Q1",s.q1,q1,colors.q1],["Med",s.q2,q2,colors.mediana],["Q3",s.q3,q3,colors.q3],["Max",s.whiskerMax,wMax,colors.ink]].forEach(([lab,val,x,col],i)=>{ctx.fillStyle=col;ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText(`${lab}: ${fmt(val)}`,x,i%2?y+66:y-58)});if(s.outliers.length){ctx.fillStyle=colors.outlier;ctx.font="bold 13px system-ui";ctx.textAlign="center";ctx.fillText(`Outliers ubicados al borde: ${s.outliers.map(fmt).join(", ")}`,width/2,y+96)}els.boxplotNote.innerHTML="<strong>Boxplot:</strong> la caja representa el 50% central. Los puntos rojos son outliers según la regla del IQR; si son extremos, se muestran al borde para no aplastar la caja."}
function drawDotplot(s){const {ctx,width,height}=setup(els.dotplotCanvas,390);clearCanvas(ctx,width,height);if(s.range===0){drawMessage(ctx,width,height,"Todos los datos son iguales; no hay dispersión.");els.dotplotNote.innerHTML="<strong>Dotplot:</strong> todos los puntos se apilan sobre el mismo valor.";return}const top=42,bottom=height-58,left=58,right=width-26,domainSeed=s.outliers.length?[s.whiskerMin,s.whiskerMax,s.lowerFence,s.upperFence]:[s.min,s.max,s.lowerFence,s.upperFence],domain=domainFrom(domainSeed,.08),mapX=mapXFactory(domain,left,right),plotX=v=>mapX(clampValue(v,domain));drawXAxis(ctx,width,height,domain,mapX,bottom,left,right);ctx.fillStyle="rgba(115,198,182,.16)";ctx.fillRect(plotX(s.q1),top,plotX(s.q3)-plotX(s.q1),bottom-top);drawVLine(ctx,plotX(s.q1),top,bottom,colors.q1,"Q1");drawVLine(ctx,plotX(s.q2),top,bottom,colors.mediana,"Med");drawVLine(ctx,plotX(s.q3),top,bottom,colors.q3,"Q3");const seen=new Map(),base=bottom-22;for(const v of s.sorted){const key=String(v),count=seen.get(key)||0;seen.set(key,count+1);const x=plotX(v),y=base-count*18;ctx.fillStyle=zoneColor(v,s);ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke();if(classify(v,s).cls==="outlier"){ctx.fillStyle=colors.outlier;ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText(fmt(v),x,y-12)}}els.dotplotNote.innerHTML="<strong>Dotplot:</strong> cada punto representa un dato real; los repetidos se apilan verticalmente y los outliers se pintan en rojo al borde si son muy extremos."}
function drawFrequencyBars(s){const {ctx,width,height}=setup(els.frequencyCanvas,430);clearCanvas(ctx,width,height);const top=44,bottom=height-72,left=54,right=width-28,items=s.frequencies,maxC=Math.max(...items.map(x=>x.count),1),gap=8,barW=Math.max(14,(right-left)/items.length-gap);ctx.strokeStyle=colors.line;ctx.beginPath();ctx.moveTo(left,bottom);ctx.lineTo(right,bottom);ctx.stroke();items.forEach((item,i)=>{const x=left+i*((right-left)/items.length)+gap/2,barH=item.count/maxC*(bottom-top);ctx.fillStyle=classify(item.value,s).cls==="outlier"?"rgba(153,27,27,.78)":"rgba(13,110,253,.72)";ctx.fillRect(x,bottom-barH,barW,barH);ctx.strokeStyle=classify(item.value,s).cls==="outlier"?colors.outlier:"#084298";ctx.strokeRect(x,bottom-barH,barW,barH);ctx.fillStyle=colors.ink;ctx.font="bold 13px system-ui";ctx.textAlign="center";ctx.fillText(String(item.count),x+barW/2,bottom-barH-6);ctx.save();ctx.translate(x+barW/2,bottom+16);ctx.rotate(items.length>12?-Math.PI/5:0);ctx.font="12px system-ui";ctx.fillStyle=colors.muted;ctx.fillText(fmt(item.value),0,0);ctx.restore()});els.frequencyNote.innerHTML=`<strong>Frecuencias:</strong> este gráfico muestra cuántas veces aparece cada valor. Hay ${items.length} valor(es) único(s).`}
function drawOrderedLine(s){const {ctx,width,height}=setup(els.orderedLineCanvas,430);clearCanvas(ctx,width,height);if(s.range===0){drawMessage(ctx,width,height,"Todos los datos son iguales; no hay dispersión.");els.orderedLineNote.innerHTML="<strong>Línea ordenada:</strong> todos los puntos quedan a la misma altura porque la lista no varía.";return}const top=42,bottom=height-58,left=58,right=width-34,domain=domainFrom([s.min,s.max],.10),mapY=v=>bottom-((v-domain.min)/(domain.max-domain.min))*(bottom-top),mapI=i=>s.n===1?left:(left+i/(s.n-1)*(right-left));ctx.strokeStyle=colors.line;ctx.beginPath();ctx.moveTo(left,bottom);ctx.lineTo(right,bottom);ctx.moveTo(left,top);ctx.lineTo(left,bottom);ctx.stroke();ctx.fillStyle=colors.muted;ctx.font="12px system-ui";ctx.textAlign="right";for(let i=0;i<=5;i++){const val=domain.min+(domain.max-domain.min)*i/5,y=mapY(val);ctx.strokeStyle="#e0effc";ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillStyle=colors.muted;ctx.fillText(fmt(val),left-8,y+4)}ctx.strokeStyle="#0d6efd";ctx.lineWidth=2;ctx.beginPath();s.sorted.forEach((v,i)=>{const x=mapI(i),y=mapY(v);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();s.sorted.forEach((v,i)=>{ctx.fillStyle=zoneColor(v,s);ctx.beginPath();ctx.arc(mapI(i),mapY(v),6,0,Math.PI*2);ctx.fill()});[["Q1",s.q1,colors.q1],["Med",s.q2,colors.mediana],["Q3",s.q3,colors.q3]].forEach(([lab,val,col])=>{const idx=s.sorted.findIndex(x=>x>=val),x=mapI(Math.max(0,idx)),y=mapY(val);ctx.fillStyle=col;ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.fillText(`${lab}: ${fmt(val)}`,x,Math.max(top+12,y-12))});els.orderedLineNote.innerHTML="<strong>Línea ordenada:</strong> los puntos conectados muestran cómo crecen los datos al ordenarlos; los saltos grandes ayudan a detectar extremos."}

function drawAllCharts(s){drawLegend();drawHistogram(s);drawBoxplot(s);drawDotplot(s);drawFrequencyBars(s);drawOrderedLine(s)}
function analyze(){try{clearError();const s=stats(parsePythonList(els.input.value));renderSummary(s);renderCasioSection(s);renderInterpretation(s);renderTable(s);drawAllCharts(s);setStatus(`${s.n} datos`)}catch(e){showError(e.message||"No se pudo analizar la lista.")}}
function clearVisuals(){els.summaryGrid.innerHTML="";els.interpretationGrid.innerHTML="";els.casioTableWrap.innerHTML="";els.casioInterpretationCard.innerHTML="";els.tableWrap.innerHTML="";[els.histogramNote,els.boxplotNote,els.dotplotNote,els.frequencyNote,els.orderedLineNote].forEach(el=>{if(el)el.innerHTML=""});[els.histogramCanvas,els.boxplotCanvas,els.dotplotCanvas,els.frequencyCanvas,els.orderedLineCanvas].forEach(canvas=>{if(canvas){const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height)}})}
els.analyzeBtn.addEventListener("click",analyze);
els.exampleStudyBtn.addEventListener("click",()=>{els.input.value="[1, 2, 2, 3, 3, 4, 4, 5, 6, 8, 20]";analyze()});
els.exampleIncomeBtn.addEventListener("click",()=>{els.input.value="[570, 1200, 590, 500, 600, 1500, 610, 550, 630, 650, 620, 580]";analyze()});
els.clearBtn.addEventListener("click",()=>{els.input.value="";clearVisuals();clearError();setStatus("Listo")});
els.showPopulation.addEventListener("change",analyze);
els.showSample.addEventListener("change",analyze);
window.addEventListener("resize",()=>{if(els.input.value.trim())analyze()});
window.addEventListener("load",analyze);
